services:
  frontend:
    build:
      context: .
      # --- BAGIAN PENTING ---
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: frontend-photography-service
    restart: always
    expose:
      - "80"
    networks:
      - private-net
    # Tambahkan ini agar docker-compose membaca file .env di host
    env_file:
      - .env

networks:
  private-net:
    external: true
